# Generated by Django 4.1 on 2022-08-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_alter_myuser_date_of_birth_alter_myuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='ifLogged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='token',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
